/* https://github.com/kojix2/bat-c */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * BatInputType enum to specify the type of input
 */
typedef enum BatInputType {
  BatBytes,
  BatFile,
  BatFiles,
} BatInputType;

/**
 * Struct to hold print options
 */
typedef struct BatPrintOptions {
  size_t tab_width;
  bool colored_output;
  bool true_color;
  bool header;
  bool line_numbers;
  bool grid;
  bool rule;
  bool show_nonprintable;
  bool snip;
  size_t wrapping_mode;
  bool use_italics;
  size_t paging_mode;
  size_t highlight_line;
} BatPrintOptions;

/**
 * Pretty print with specified options.
 */
void bat_pretty_print(const char *input,
                      size_t length,
                      enum BatInputType input_type,
                      const char *language,
                      const char *theme,
                      struct BatPrintOptions options);

/**
 * Pretty print output to a string.
 */
const char *bat_pretty_print_to_string(const char *input,
                                       size_t length,
                                       enum BatInputType input_type,
                                       const char *language,
                                       const char *theme,
                                       struct BatPrintOptions options,
                                       size_t *output_length);

/**
 * Free the string allocated by `bat_pretty_print_to_string`.
 */
void bat_free_string(const char *s);

/**
 * Return the version of the library
 */
const char *bat_c_version(void);
